### ISSUE TITLE
Engine flags are incorrect for exportJSONEntityReport call

### ISSUE THREAD

**Issue by antaenc** [Senzing/resolver#65]
The call to exportJSONEntityReport to collect the export data is using incorrect flags:

`flags = G2Engine.G2_EXPORT_INCLUDE_ALL_ENTITIES | G2Engine.G2_ENTITY_INCLUDE_RECORD_MATCHING_INFO | G2Engine.G2_EXPORT_INCLUDE_ALL_RELATIONSHIPS | G2Engine.G2_ENTITY_INCLUDE_RELATED_MATCHING_INFO`

as such relationships are not being included in the output. Flags should be changed to:

`flags = G2Engine.G2_EXPORT_INCLUDE_ALL_ENTITIES | G2Engine.G2_ENTITY_BRIEF_DEFAULT_FLAGS`

**Comment by docktermj** [comment]
Fixed in https://github.com/Senzing/resolver/issues/73
