### ISSUE TITLE
Add flags to the json output

### ISSUE THREAD

**Issue by jbutcher21** [Senzing/resolver#69]
Something like this would be nice ...

dynamic_url = 'http://xps8920:8252/resolve**?withJson=true&withFeatures=true**'

  withJson=true  //sets g2_engine.G2_ENTITY_INCLUDE_RECORD_JSON_DATA
  withFeatures=true  // sets g2_engine.G2_ENTITY_INCLUDE_ALL_FEATURES

This will allow a user to pass in a file and get the actual data back out.   As it is now, they only get the keys (record Ids) and would have to lookup the data themselves (in their own repository as we have already purged the records!)

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/resolver/pull/70
